#!/usr/bin/env python3

import hashlib
import json
import os
import urllib.request
from datetime import datetime, timedelta, timezone
from pathlib import Path

CALENDAR_PATH = Path("gw2-events.ics")
API_URL = "https://api.guildwars2.com/v2/characters?ids=all"

BEGIN_MARKER = "X-GW2-CHARACTER-BIRTHDAY:TRUE"


def fetch_characters(api_key: str) -> list[dict]:
    req = urllib.request.Request(
        API_URL,
        headers={
            "Authorization": f"Bearer {api_key}",
            "User-Agent": "MallarDev/gw2-events-calendar",
        },
    )

    with urllib.request.urlopen(req, timeout=30) as response:
        return json.load(response)


def parse_created(value: str) -> datetime:
    return datetime.fromisoformat(value.replace("Z", "+00:00")).astimezone(timezone.utc)


def next_birthday(created: datetime, now: datetime) -> tuple[datetime, int]:
    # GW2 character birthdays happen every 365 days from character creation.
    elapsed_seconds = max(0.0, (now - created).total_seconds())
    completed_periods = int(elapsed_seconds // (365 * 86400))

    number = completed_periods + 1
    birthday = created + timedelta(days=365 * number)

    while birthday <= now:
        number += 1
        birthday = created + timedelta(days=365 * number)

    return birthday, number


def escape_ics(value: str) -> str:
    return (
        value.replace("\\", "\\\\")
        .replace("\n", "\\n")
        .replace(";", "\\;")
        .replace(",", "\\,")
    )


def stable_uid(name: str) -> str:
    digest = hashlib.sha256(name.encode("utf-8")).hexdigest()[:20]
    return f"gw2-character-{digest}@mallardev"


def make_event(character: dict, now: datetime) -> tuple[datetime, str]:
    name = character["name"]
    created = parse_created(character["created"])
    birthday, birthday_number = next_birthday(created, now)

    created_label = created.strftime("%d/%m/%Y %H:%M UTC")

    lines = [
        "BEGIN:VEVENT",
        f"UID:{stable_uid(name)}",
        f"DTSTAMP:{now.strftime('%Y%m%dT%H%M%SZ')}",
        f"DTSTART:{birthday.strftime('%Y%m%dT%H%M%SZ')}",
        "DURATION:PT1H",
        "RRULE:FREQ=DAILY;INTERVAL=365",
        BEGIN_MARKER,
        f"SUMMARY:🎂 {escape_ics(name)} — {birthday_number}º Birthday Gift",
        (
            "DESCRIPTION:"
            f"Birthday Gift do personagem {escape_ics(name)}. "
            f"Criado em {created_label}. "
            "No Guild Wars 2 o aniversário do personagem ocorre a cada 365 dias."
        ),
        "CATEGORIES:Guild Wars 2,Character Birthday",
        "END:VEVENT",
    ]

    return birthday, "\n".join(lines)


def remove_generated_birthdays(calendar: str) -> str:
    lines = calendar.splitlines()
    output: list[str] = []
    event: list[str] | None = None

    for line in lines:
        if line == "BEGIN:VEVENT":
            event = [line]
            continue

        if event is not None:
            event.append(line)

            if line == "END:VEVENT":
                block = "\n".join(event)

                # Only removes events generated by this script.
                if BEGIN_MARKER not in block:
                    output.extend(event)

                event = None

            continue

        output.append(line)

    if event is not None:
        output.extend(event)

    return "\n".join(output).rstrip() + "\n"


def main() -> None:
    api_key = os.environ.get("GW2_API_KEY")

    if not api_key:
        raise SystemExit("Missing GW2_API_KEY")

    now = datetime.now(timezone.utc)
    characters = fetch_characters(api_key)

    calendar = CALENDAR_PATH.read_text(encoding="utf-8")
    calendar = remove_generated_birthdays(calendar)

    if not calendar.rstrip().endswith("END:VCALENDAR"):
        raise SystemExit("Invalid gw2-events.ics: END:VCALENDAR not found")

    events = [make_event(character, now) for character in characters]
    events.sort(key=lambda item: (item[0], item[1]))

    body = calendar.rstrip()
    body = body[: -len("END:VCALENDAR")].rstrip()

    if events:
        body += "\n\n" + "\n\n".join(event for _, event in events)

    body += "\n\nEND:VCALENDAR\n"

    CALENDAR_PATH.write_text(body, encoding="utf-8", newline="\n")

    print(f"Characters returned by GW2 API: {len(characters)}")
    print(f"Birthday events written: {len(events)}")


if __name__ == "__main__":
    main()
